apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "caleon.fullname" . }}-anterior
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "caleon.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "calean.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/vault: {{ include (print $.Template.BasePath "/configmap-vault.yaml") . | sha256sum }}
    spec:
      securityContext: {{- toYaml .Values.security | nindent 8 }}
      containers:
        - name: anterior
          image: "{{ .Values.image.registry }}/anterior-helix:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8001
          env:
            - name: SEED_VAULT_PATH
              value: /app/seed_vault
            - name: RUNTIME_PATH
              value: /app/runtime
          volumeMounts:
            - name: vault
              mountPath: /app/seed_vault
              readOnly: true
            - name: runtime
              mountPath: /app/runtime
          resources: {{- toYaml .Values.resources.anterior | nindent 12 }}
      volumes:
        - name: vault
          configMap:
            name: {{ include "caleon.fullname" . }}-vault
        - name: runtime
          emptyDir: {}